using OrderService.Domain.Common;
using OrderService.Domain.Events;
using OrderService.Domain.Exceptions;

namespace OrderService.Domain.Entities;

/// <summary>A customer purchase request (spec FR-003, FR-006, FR-008). See data-model.md for the state
/// machine this aggregate enforces.</summary>
public class Order : AggregateRoot
{
    private readonly List<OrderLineItem> _lineItems = new();
    private readonly List<OrderStatusHistory> _statusHistory = new();

    public string UserId { get; private set; } = default!;
    public OrderStatus Status { get; private set; }
    public IReadOnlyCollection<OrderLineItem> LineItems => _lineItems.AsReadOnly();
    public IReadOnlyCollection<OrderStatusHistory> StatusHistory => _statusHistory.AsReadOnly();
    public decimal TotalAmount => _lineItems.Sum(li => li.LineTotal);
    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }

    private Order() { } // EF Core

    /// <summary>orderId is pre-generated by the caller (PlaceOrderCommandHandler) so that stock reservations
    /// made against Product Service before the aggregate exists already reference the order's final id.</summary>
    public static Order Place(Guid orderId, string userId, IReadOnlyCollection<OrderLineItem> lineItems)
    {
        if (string.IsNullOrWhiteSpace(userId)) throw new DomainException("UserId is required.");
        if (lineItems is null || lineItems.Count == 0)
            throw new DomainException("An order must contain at least one line item.");

        var order = new Order
        {
            Id = orderId,
            UserId = userId,
            Status = OrderStatus.Placed,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };

        foreach (var lineItem in lineItems)
        {
            lineItem.AttachToOrder(order.Id);
            order._lineItems.Add(lineItem);
        }

        order._statusHistory.Add(new OrderStatusHistory(order.Id, null, OrderStatus.Placed, userId));
        order.Raise(new OrderStatusChangedDomainEvent(order.Id, null, OrderStatus.Placed, userId));

        return order;
    }

    /// <summary>Enforces the transition table in data-model.md. Any transition not listed is rejected (FR-006).</summary>
    private static readonly Dictionary<OrderStatus, OrderStatus[]> AllowedTransitions = new()
    {
        [OrderStatus.Placed] = new[] { OrderStatus.Confirmed, OrderStatus.Cancelled },
        [OrderStatus.Confirmed] = new[] { OrderStatus.Shipped, OrderStatus.Cancelled },
        [OrderStatus.Shipped] = new[] { OrderStatus.Delivered },
        [OrderStatus.Delivered] = Array.Empty<OrderStatus>(),
        [OrderStatus.Cancelled] = Array.Empty<OrderStatus>()
    };

    /// <summary>Returns the new OrderStatusHistory row so the caller (ChangeOrderStatusCommandHandler) can
    /// explicitly hand it to the repository — EF Core's change-tracker graph walk does not reliably detect a
    /// new child appended to a collection navigation on an aggregate that was already tracked from a prior
    /// query (as opposed to a brand-new aggregate added via AddAsync, where the whole graph is cascaded as
    /// Added), so relying on it here previously produced a spurious UPDATE instead of an INSERT.</summary>
    public OrderStatusHistory ChangeStatus(OrderStatus newStatus, string changedBy)
    {
        if (!AllowedTransitions.TryGetValue(Status, out var allowed) || !allowed.Contains(newStatus))
        {
            throw new InvalidOrderStatusTransitionException(Status.ToString(), newStatus.ToString());
        }

        var previousStatus = Status;
        Status = newStatus;
        UpdatedAt = DateTimeOffset.UtcNow;

        var history = new OrderStatusHistory(Id, previousStatus, newStatus, changedBy);
        _statusHistory.Add(history);
        Raise(new OrderStatusChangedDomainEvent(Id, previousStatus, newStatus, changedBy));

        if (newStatus == OrderStatus.Cancelled)
        {
            Raise(new OrderCancelledDomainEvent(Id, LineItems));
        }

        return history;
    }
}
