import {
  CreateProductRequest,
  PagedResult,
  Product,
  ProductStatus,
  UpdateProductRequest,
} from '@frontend/shared-models';
import { throwIfNotOk } from './api-error';

// Typed client for contracts/product-service.openapi.yaml, generated by hand to mirror the OpenAPI contract
// exactly (architecture.md §2.1's libs/shared/api-clients). Framework-agnostic — used by both order-app
// (Angular) and product-app (Vue).
export class ProductApiClient {
  constructor(
    private readonly baseUrl: string,
    private readonly getAuthToken: () => string | null
  ) {}

  private headers(): HeadersInit {
    const token = this.getAuthToken();
    return {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    };
  }

  async search(query?: string, status?: ProductStatus, page = 1, pageSize = 20): Promise<PagedResult<Product>> {
    const params = new URLSearchParams();
    if (query) params.set('q', query);
    if (status) params.set('status', status);
    params.set('page', String(page));
    params.set('pageSize', String(pageSize));

    const response = await fetch(`${this.baseUrl}/product-service/v1/products?${params}`, {
      headers: this.headers(),
    });
    await throwIfNotOk(response);
    return response.json();
  }

  async getById(productId: string): Promise<Product> {
    const response = await fetch(`${this.baseUrl}/product-service/v1/products/${productId}`, {
      headers: this.headers(),
    });
    await throwIfNotOk(response);
    return response.json();
  }

  async create(request: CreateProductRequest): Promise<Product> {
    const response = await fetch(`${this.baseUrl}/product-service/v1/products`, {
      method: 'POST',
      headers: this.headers(),
      body: JSON.stringify(request),
    });
    await throwIfNotOk(response);
    return response.json();
  }

  async update(productId: string, request: UpdateProductRequest): Promise<Product> {
    const response = await fetch(`${this.baseUrl}/product-service/v1/products/${productId}`, {
      method: 'PATCH',
      headers: this.headers(),
      body: JSON.stringify(request),
    });
    await throwIfNotOk(response);
    return response.json();
  }

  async retire(productId: string): Promise<Product> {
    const response = await fetch(`${this.baseUrl}/product-service/v1/products/${productId}/retire`, {
      method: 'POST',
      headers: this.headers(),
    });
    await throwIfNotOk(response);
    return response.json();
  }
}
